### ISSUE TITLE
Secure resources from CNCF Infra lab and/or cloud credits

### ISSUE THREAD

**Issue by halcyondude** [observe-k8s/hub#22]

**Comment by halcyondude** [comment]
Resources to review:

* https://www.cncf.io/community-infrastructure-lab
* https://github.com/CNCF/cluster
TLDR: Ask

* k8s cluster(s), either BM or cloud hosted (EKS, GKE, AKS, ...)
* GitOps workflows assumed (flux, argo, etc)

Start here: https://github.com/cncf/cluster/issues/new

**Comment by kenfinnigan** [comment]
Created the request: https://github.com/cncf/cluster/issues/212
